version: '3.3'
services:
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword1
      POSTGRES_DB: testdb
    hostname: postgres
    restart: always
    user: root
    tty: true
    volumes:
      - ./pgsql:/var/lib/postgresql/data
